Add user agent header
inloco/incognia-api-java pull request #80
Opened 2022-06-22 21:26 UTC by gabmei

## Proposed changes

This PR adds header information to indicate requests from java wrapper. Header information follows the format
`<library-name>/<library-version> (<os-name> <os-version> <os-arch>) <language-name>/<language-version>`
A `ProjectVersion.java` file is created with a `PROJECT_VERSION` field before compilation to access the library version

## Checklist
- [X] Style check and tests pass locally with my changes
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] I have added necessary documentation (if appropriate)

2022-06-23 15:57 UTC, joaoaab requested changes

2022-06-23 15:57 UTC, joaoaab commented on build.gradle
> +public class ProjectVersion {
I think we can indent these part better, it's very difficult to read whats being created here

2022-06-23 15:57 UTC, joaoaab commented on src/main/java/com/incognia/api/clients/TokenAwareNetworkingClient.java
> +  private String buildUserAgentHeader() {
i think this only needs to be built once, so this could be a static constant in the class i think

2022-06-27 21:27 UTC, figueredo approved these changes

2022-06-27 21:27 UTC, figueredo commented on src/main/java/com/incognia/api/clients/TokenAwareNetworkingClient.java
> +        new HashMap<String, String>() {
optional: another short replacement for `Collections.singletonMap` is `Map.of`

2022-06-30 13:48 UTC, merged